# Podfile
platform :ios, '10.0'
use_frameworks!

target 'SOLOWallet-ios' do

  pod 'MMDrawerController', '~> 0.5.7'
  pod 'KeychainAccess', '~> 3.1.0'
  pod 'JDStatusBarNotification', '~> 1.5.6'
  pod 'Texture', '~> 2.6'

  pod 'SoloSDK', path: '../sdk/ios/SoloSDK'
  
  # A tool to enforce Swift style and conventions
  pod 'SwiftLint'
end
