# Podfile
platform :ios, '9.1'
use_frameworks!

target 'SOLOWallet-ios' do

  pod 'MMDrawerController', '~> 0.5.7'
  pod 'SideMenu', '~> 3.0.2'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'Alamofire', '~> 4.5.1'
  pod 'KeychainAccess', '~> 3.1.0'
  pod 'JDStatusBarNotification', '~> 1.5.6'
  pod 'Texture', '~> 2.6'
  
end
