# Podfile
platform :ios, '10.0'
use_frameworks!

target 'SoloSDK' do
    
    pod 'Alamofire', '~> 4.5.1'
    
    target 'SoloSDKTests' do
        inherit! :search_paths
        # Pods for testing
    end
end
